### ISSUE TITLE
Complete the introduction of different `Applications` 

### ISSUE THREAD

**Issue by pfliu-nlp** [inspired-co/Inspired-walkthroughs#3]
We will have current organization:
* Applications
    - automated_evaluation
    - model_analysis
    - benchmarking
It would be nice if we completed corresponding descriptions for each application.

**Comment by neubig** [comment]
I think this issue is probably too broad. Could you please split it into sub-issues for each of these?

**Comment by pfliu-nlp** [comment]
thanks for the suggestions and done.
